import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import Providers from './Providers'
import Navbar from './components/Navbar'
import SearchSection from './components/SearchSection'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {}
          <Header/>
          {}
          <Navbar/>
          {}
          <SearchSection/>
        
        
          {children}
        </Providers>
        
        </body>
    </html>
  )
}
